### ISSUE TITLE
агенты умирают

### ISSUE THREAD

**Issue by LuninaPolina** [ShalamovRoman/Tachki#2]
земля им пухом
царствие им небесное

**Comment by SusaninaJulia** [comment]
Придет пора преображенья,
Конец житейского пути,
Предсмертной муки приближенье
Заслышу в ноющей груди,
И снидет ангел к изголовью,
Крестом трикраты осеня,
С неизъяснимою любовью
И грустью взглянет на меня.

**Comment by LuninaPolina** [comment]
скорбим

**Comment by SusaninaJulia** [comment]
у них герпес просто

**Comment by ShalamovRoman** [comment]
Они будут жить
