### ISSUE TITLE
требуется программист

### ISSUE THREAD

**Issue by LuninaPolina** [ShalamovRoman/Tachki#3]
Существующего необходимо незамедлительно уволить!
Код отвратителен, не соответствует ни одному золотому правилу объектно-ориентированного программирования, логика отсутствует в принципе как концепция. Читать противно, вызывает рвотный рефлекс от первой до последней строчки.
Даже бухгалтер на калькуляторе или трехлетний ребенок на слюнявчике бы лучше написал!!!

**Comment by SusaninaJulia** [comment]
должность системного аналитика тоже под вопросом, так как ранее он сравнивается с трехлетним ребенком
один алгоритмист молодец, однако это ведет к другой проблеме, рассмотренной в более поздних issues

**Comment by LuninaPolina** [comment]
более того главный программист слишком много рофлит над собственным кодом, из -за чего значительно ухудшается скорость общей работы

**Comment by LuninaPolina** [comment]
зато код смешной @LuninaPolina (главный программист)

**Comment by SusaninaJulia** [comment]
Программист слишком много поёт (и слишком плохо)  сюзанну

**Comment by LuninaPolina** [comment]
СЮЗАНННННННННННННАААААААА СЮЗАААААААААААААААААААААААНА МОН АМУУР

**Comment by LuninaPolina** [comment]
программист забывает слово, которое ему надо напечатать, пока печатает его

**Comment by LuninaPolina** [comment]
и агент опять сдох(((
