### ISSUE TITLE
Нереализуемость алгоритма

### ISSUE THREAD

**Issue by SusaninaJulia** [ShalamovRoman/Tachki#7]
Как уже упоминалось, реализация алгоритма, созданного одним из участников команды, вызывает некоторые трудности
Основной проблемой является неспособность остальной команды понять принцип работы выше упомянутого алгоритма и вообще разобраться в записях, сделанных главным алгоритмистом

**Comment by LuninaPolina** [comment]
На мой непросвященный взгляд, основной проблемой является не это, а как раз таки необъятное самолюбие так называемого "главного алгоритмиста", неспособного найти общий язык с командой, которая, в отличие от некоторых, всегда распахнута навстречу новым алгоритмам.
