### ISSUE TITLE
Слишком много проблем

### ISSUE THREAD

**Issue by SusaninaJulia** [ShalamovRoman/Tachki#8]
За перечислением проблем, действующая часть команды, забыла, что они должны делать

**Comment by LuninaPolina** [comment]
Совершенно согласна. Как гласит эфиопская народная мудрость "jgkrvhbgawkag vgbjeavblhs fsbhksgb ghsgj", что в грубом переводе означает "мультиагентная система, в которой ишью больше, чем кода, должна быть незамедлительно удалена во избежание конца света".
